language: python
python:
  - "3.6"
services: 
  - postgresql
env:
  - DJANGO=3.1 DB=postgresql log_path_django=$HOME/
before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - pwd
  - touch $HOME/not-found-products.log
  - psql -U postgres -c "CREATE USER david WITH PASSWORD 'test';" -U postgres
  - psql -U postgres -c "ALTER ROLE david CREATEDB;" -U postgres
  - psql -U postgres -c "ALTER ROLE david superuser;" -U postgres
  - psql -U postgres -c "CREATE DATABASE dbtest;" -U postgres
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=search ./manage.py test
  - python ./search/tests/selenium_tests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
