language: python
python:
  - "3.6"
services: 
  - postgresql
env:
  - DJANGO=3.1 DB=postgre
before_script:
  - psql -c 'create database test_db;' -U postgres
install:
  - pip install -r requirements.txt
script:
  - python manage.py test search