# Generated by Django 3.1.1 on 2020-10-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20201004_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
