# Generated by Django 3.1.1 on 2020-10-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20201004_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='resume',
            field=models.CharField(max_length=1000),
        ),
    ]
