# Generated by Django 3.1.1 on 2020-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20201006_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
