# Generated by Django 3.1.1 on 2020-10-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_product_category_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_ref',
        ),
    ]
