# Generated by Django 3.1.1 on 2020-10-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20201006_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='na', max_length=50),
        ),
    ]
