# Generated by Django 3.1.1 on 2020-10-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20201006_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutriscore_grade',
            field=models.CharField(max_length=2),
        ),
    ]
