# Generated by Django 3.1.1 on 2020-10-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20201006_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
